"""add site content

Revision ID: b2fa21fdf64c
Revises: e3f741e7cac0
Create Date: 2026-08-19 00:46:21.108694

"""
from alembic import op
import sqlalchemy as sa

from app.crud.site_content import DEFAULT_SITE_CONTENT


# revision identifiers, used by Alembic.
revision = 'b2fa21fdf64c'
down_revision = 'e3f741e7cac0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    site_content_table = sa.table(
        "site_content",
        sa.column("id", sa.Integer),
        sa.column("data", sa.JSON),
    )
    op.bulk_insert(site_content_table, [{"id": 1, "data": DEFAULT_SITE_CONTENT}])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_content')
    # ### end Alembic commands ###
